export const allData = {
    isSalesEnabled: false,
    salesText: {
        main: 'Цены июня на начало июля!',
        additional: '*Низкие цены до 15 июля',
    },
    salesMonths: {
        april: false,
        may: false,
        june: false,
        july: false,
        august: false,
        september: false,
        october: false,
    },
    priceYear: 2024,
    standard: [
        {month: 'april', price: 1500},
        {month: 'may', price: 2000},
        {month: 'june', price: 3000},
        {month: 'july', price: 5000},
        {month: 'august', price: 6000},
        {month: 'september', price: 5500},
        {month: 'october', price: 2000},
    ],
    semiLuxurySeaView: [
        {month: 'april', price: 2000},
        {month: 'may', price: 2500},
        {month: 'june', price: 3500},
        {month: 'july', price: 6000},
        {month: 'august', price: 7000},
        {month: 'september', price: 6000},
        {month: 'october', price: 2500},
    ],
    semiLuxuryFamily: [
        {month: 'april', price: 2500},
        {month: 'may', price: 3000},
        {month: 'june', price: 4500},
        {month: 'july', price: 7500},
        {month: 'august', price: 8000},
        {month: 'september', price: 7000},
        {month: 'october', price: 3000},
    ],
}
